### ISSUE TITLE
REV Checklist Issues

### ISSUE THREAD

**Issue by ericorosel** [sparkfun/Hall-Effect_Current_Sensor_Breakout-ACS712#6]
1) ACS712 needs proper prefix (currently JP which is used for connectors and headers)

2) Board frame is 10mil instead of 8mil, for consistency's sake, I think it should be 8mil. 

3) Max Current Silk is incorrect, check with ENG. to see what this value should be. Per the DS, the max  for the chip is around +-5A depending on the ambient temp. I think the PCB's traces would cook if 5A were driven through them, but I could be wrong. We may also want to label the max isolation, per the DS, the chip has a 2.1kVrms Isolation, but I think the board could have a lower isolation voltage. In short: check with eng on these characteristic values.

**Comment by PatrickAlberts** [comment]
Yo I made the changes, based on the trace width calculator and the max amperage for the chip (according to the data sheet) the max amerage is 13mA.  The trace width accounts for that amperage, any more width will cause a DRC error.  In the bug we decided the isolation, does not need to be on the board silk, but will remain on the product description.  All other issues fixed.

**Comment by lewispg228** [comment]
Hey Toni, 

1) the silk on this still shows 13mA. I'm not sure where this number came from, but this thing can sense up to 5A of current. Please correct. I think adding a note in the schematic would be a good idea too.

2) voltage range for VCC would be a good note in the sch too. The datasheet doesn't specify a min VCC, but it does say the max is 8V. (Maybe we could just put a note in the SCH for 5-7V). Has anyone tried this IC at 3.3V?

**Comment by ToniCorinne** [comment]
I fixed the 13mA (the supply  current max) to 5A on the silk, and added a note in the schematic.

The recommended operating conditions per the datasheet is 4.5-5.5V, so I think the label that is already above VCC at 5VDC is sufficient. I can test it at 3.3V on the protos, but for our documentation, I'd like to stick with what the datasheet says currently.

**Comment by lewispg228** [comment]
Right on. Thanks Toni!
