### ISSUE TITLE
Double Check v01

### ISSUE THREAD

**Issue by edspark** [sparkfun/Hall-Effect_Current_Sensor_Breakout-ACS712#8]
1) The jumper in the schematic is not labeled with its function. "Bandwidth Frequency" would help clarify the two possible settings of 20kHz and 80kHz that is already on the board and make it easier to see which setting is being pulled high and the other to GND. 

2) This isn't an issue but I don't think this GND via offers much utility so close to the GND through-hole: 
![gnd](https://user-images.githubusercontent.com/18684691/33788886-1f8abb66-dc32-11e7-8eae-0e88e54ec458.JPG)

**Comment by ericorosel** [comment]
-Added BW-SEL note in SCH
-Removed redundant via
